### ISSUE TITLE
programmatic access to band structure in Python

### ISSUE THREAD

**Issue by stevengj** [NanoComp/mpb#103]
Right now, the Python interface only provides access to `freqs` for the last computed band, and the tutorial outputs to a file and uses `grep` to plot the bands much like was done for the stand-alone Scheme program.

It would be a lot more convenient to be able to access the same data directly from Python, e.g. after each `run` command have something that stores all of the frequencies for you in a matrix, analogous to `all-freqs` in Scheme.

cc @ChristopherHogan

**Comment by ChristopherHogan** [comment]
I think I already store this information in `ModeSolver.all_freqs`. It's a numpy array that stores the frequencies for each band. https://github.com/NanoComp/meep/blob/master/python/solver.py#L913

**Comment by stevengj** [comment]
Ah, great. Is it documented?
