### ISSUE TITLE
Distortion of blocks in a triangular array

### ISSUE THREAD

**Issue by Andbarz** [NanoComp/mpb#113]
I'm trying to simulate the photonic bands of a 2D structure made of blocks (i.e. squares) arranged in a triangular lattice. I'm using the python interface and the latest release of MPB.

I'm a pretty new user so I've started by modifying the mpb_tri_rods.py file from the Data Anlysis tutorial (see https://mpb.readthedocs.io/en/latest/Python_Data_Analysis_Tutorial/). That tutorial shows that the dielectric function returned by get_epsilon() is distorted due to the fact that the cell of our lattice is no longer a square, and uses the convert() function from a MPBData instance (with rectify=True) to correct that.

However, now that I'm working on squares, that doesn't happen: if I plot the raw dielectric costant data (e.g. by matplotlib's matshow()) I get a perfect square, while rectify=True distorts the squares into parallelograms.
I guess this is a bug?

**Comment by stevengj** [comment]
The block basis vectors are in the lattice basis, so the blocks are affine by default if the basis is affine.   Change the basis vectors e1/e2/e3 of the blocks to whatever you want (e.g. using cartesian->lattice to specify them in cartesian coordinates).
