### ISSUE TITLE
Arguments for field arrays in MPB Data Analysis

### ISSUE THREAD

**Issue by JohnWeiner** [NanoComp/mpb#115]
Here are a couple of lines from the Data Analysis MPB tutorial:
for f in efields:
    # Get just the z component of the efields
    f = f[..., 0, 2]
This is undoubtedly a rookie question, but what does the 0 argument mean?  I presume the last argument, 2, is the axis (x->0, y->1, z->2), but I have not been able to find the meaning of the next-to-last argument in the read-the-docs documentation of the MPBArray or get functions or Googled documentation (StackOverflow, etc.) on numpy array attributes.

**Comment by stevengj** [comment]
It's the same as `f[:, :, 0, 2]`.  `f` is a 4d array (X x Y x Z x 3), where the Z direction has only 1 pixel (since this is a 2d calculation), so by passing `0` for the Z index we are taking the 2d (X x Y) slice corresponding to Ez (2).

**Comment by JohnWeiner** [comment]
Thanks, got it.  I didn’t know about the Ellipse object or the multidimensional indexing.  Much clearer now.
