### ISSUE TITLE
Configure fails with error: could not find gen-ctl-io program; check your PATH.

### ISSUE THREAD

**Issue by mariswow** [NanoComp/mpb#124]
Hello,

I trying to compile MPB from source on a HPC unit that is running CentOS 7.

The installed guile version is 2.0.9 and libctl 4.2.0. I have also tried installing the most recent version of libctl, 4.5.0, but it still failed with the same error. I checked the path and in the bin directory, there is a gen-ctl-io.

I have attached the full config.log.
[config.log](https://github.com/NanoComp/mpb/files/5305601/config.log)

Regards,
Marius

**Comment by stevengj** [comment]
What happens if you type `gen-ctl-io` at your shell prompt?

**Comment by mariswow** [comment]
Sorry for wasting your time, I just had to add the PATH to where libctl was installed.

Thank you for your help nonetheless.
