### ISSUE TITLE
confusion about TE/TM separation in output

### ISSUE THREAD

**Issue by nblinov** [NanoComp/mpb#147]
Hello,

I'm trying to develop some intuition for mode functions in simple dielectric structures computed with MPB starting with some basic examples, but it appears that the modes do not cleanly separate into TM/TE. Here's an example:
I set up a MPB run with a dielectric slab in the xy plane and compute the modes propagating in the x direction with run_te or run_tm. On plotting the mode profiles I see that, e.g. for some TE modes there is a non-zero component along x, contrary to the definition of TE. 
Similarly, for TM, there can be a non-zero component along the propagation directon. Moreover the presence or absence of these "wrong" field components seems to alternate with the band number. 
On the other hand, checking the first few eigenfrequencies yields agreement with semianalytic calculations. 
Here's the set-up for the calculation:
```
geometry_lattice = mp.Lattice(size=mp.Vector3(0,0,4))
geometry = [mp.Block(size=mp.Vector3( mp.inf,  mp.inf, 1),
                     center=mp.Vector3(), material=mp.Medium(index=2.21))]
num_bands = 3
num_k = 20
k_min = 0.1
k_max = 5.0
k_points = mp.interpolate(num_k, [mp.Vector3(k_min), mp.Vector3(k_max)])

ms = mpb.ModeSolver(
    geometry_lattice=geometry_lattice,
    geometry=geometry,
    k_points=k_points,
    resolution=64,
    num_bands=num_bands)
```

I run into similar confusion for rectangular and ridge waveguides, so I am concerned that when move on to anisotropic dielectric tensors the "wrong" field components will change eigenfrequencies in some surprising way. Am I severely confused about what MPB is computing (i.e. may be some linear combination of a degenerate pair of eigenmodes that is not purely TM or TE) or is there a way to force it to adhere to the usual TM/TE conventions? 

Thank you for your help!

**Comment by stevengj** [comment]
Beware that there are varying definitions of "TE/TM" in the literature.

In MPB, by "TE" we mean (in a 2d simulation, i.e. z-invariant structures) electric fields in the xy plane and H in z, whereas by "TM" we mean the opposite (H in xy and E in z). 

That is the only polarization decomposition you can generally expect.

**Comment by nblinov** [comment]
Hi Thomas and Steven, 
thanks for you help - I think my main hang up was the different convention for TE/TM (I was used to these defined with respect to the propagation direction, not a fixed axis). 

Re: lattice size, I was following the conventions in the first example shown here http://www.simpetus.com/projects.html#mpb_waveguide for the ridge waveguide which has
`geometry_lattice = mp.Lattice(size=mp.Vector3(0,sc_y,sc_z))`
This appears to be consistent with some statements in the tutorial (https://mpb.readthedocs.io/en/latest/Python_Tutorial/), i.e. "we can set some of the dimensions to have a size 0". Is this syntax deprecated?

**Comment by thchr** [comment]
> Re: lattice size, I was following the conventions in the first example shown here http://www.simpetus.com/projects.html#mpb_waveguide for the ridge waveguide which has `geometry_lattice = mp.Lattice(size=mp.Vector3(0,sc_y,sc_z))` This appears to be consistent with some statements in the tutorial (https://mpb.readthedocs.io/en/latest/Python_Tutorial/), i.e. "we can set some of the dimensions to have a size 0". Is this syntax deprecated?

I was just not aware of this syntax: cool, today I learned!
