### ISSUE TITLE
helix arrays in MPB

### ISSUE THREAD

**Issue by ywsun868** [NanoComp/mpb#153]
How I can create helix arrays in MPB. I don't know what equation a continuous 3D helix 
![2022-10-03_225414](https://user-images.githubusercontent.com/69755365/193608622-814f7f10-5a15-4b0d-8d6c-dcc286fe5878.jpg)
should satisfy.

**Comment by stevengj** [comment]
For something like this I would just define your own ε(x,y,z) function and use it as an `epsilon_func`
