### ISSUE TITLE
integral in MPB

### ISSUE THREAD

**Issue by ywsun868** [NanoComp/mpb#155]
Hello：
 If I  don't want the integral over the whole cell, how to integral of f along a line or area in MPB. 
Thank you for help!!!

**Comment by stevengj** [comment]
You can use the `*_field_get_point` functions from [here](https://mpb.readthedocs.io/en/latest/Python_User_Interface/#storing-and-combining-multiple-fields) to evaluate any field at any arbitrary point in space, and then integrate it over e.g. a line or area with the trapezoidal rule.

**Comment by ywsun868** [comment]
Thanks a lot, it exactly helps me!
