### ISSUE TITLE
Syntax error during `make check` for Guile 2.27

### ISSUE THREAD

**Issue by oskooi** [NanoComp/mpb#162]
When building MPB from source using [Guile 2.2.7](https://lists.gnu.org/archive/html/guile-devel/2020-03/msg00009.html) (the version installed with the precompiled binary `guile-2.2-dev` on Ubuntu 22.04), an error occurs during `make check`:
```
ice-9/boot-9.scm:222:17: In procedure map1:
Syntax error:
../examples/check.ctl:331:2: definition in expression context, where definitions are not allowed, 
in form (define symeigs-inv (compute-symmetries W w))
```

**Comment by thchr** [comment]
This is my mistake. When I was doing #134, I was compiling with Guile 3.0 or 3.1 and wasn't aware/did not remember that this syntax was disallowed on earlier versions.

I have time to look at this Friday this week or Monday next week (but if you need a fix sooner, of course, don't wait).

**Comment by thchr** [comment]
Okay, seems like the issue was very small: see #163.

I didn't check on Guile 2.27 in practice though, since I don't have that version: I'm assuming that's also not tested what is tested by CI?

**Comment by oskooi** [comment]
> maybe there is no CI here on the mpb repo - only meep?

There used to be CI for the MPB repo using [Travis](https://github.com/NanoComp/mpb/blob/master/.travis.yml). Since the Python  API for MPB is provided by Meep, the Meep CI using Github Actions does include a [unit test](https://github.com/NanoComp/meep/blob/master/python/tests/test_mpb.py). However, currently there is no test for the Scheme API for MPB. This is why this error went undetected.
