### ISSUE TITLE
Inputting dielectric contant

### ISSUE THREAD

**Issue by Saranyanarayanan** [NanoComp/mpb#76]
How do I specify the dielectric constant of the medium? what if I want to fill my structure with some other material?

**Comment by ismailkalay** [comment]
i did not try but you can add .h5 file epsilon according to x, y ,z coordinates. 
[(https://meep.readthedocs.io/en/latest/Scheme_User_Interface/)](url)
`(meep-structure-load structure "oled-epsilon.h5")))`
[http://www.simpetus.com/projects_scheme.html]

I could not find adding material epsilon(frequency) as a file. in MEEP you can add epsilon value according to frequency.

**Comment by stevengj** [comment]
MPB does not support frequency-dependent (dispersive) materials.  You can input any nondispersive ε(x,y,z) you want, as explained in the manual and tutorials.
