### ISSUE TITLE
Build --with-libctl misleading directory

### ISSUE THREAD

**Issue by zerothi** [NanoComp/mpb#89]
typically when building with configure the `--with-<package>=<dir>` means the base-path installation of the said package.

However, in mpb the configure script assumes `--with-libctl=/opt/libctl/share/libctl`, i.e. an extra `share/libctl` suffix which is counter intuitive.

I would suggest you to allow `-with-libctl=<dir>` also check the sub-folder `<dir>/share/libctl` to make it more compliant with configure scripts?

Also, `configure --help` does not clarify this issue.

Thanks!

**Comment by stevengj** [comment]
Checking the `share/libctl` subfolder is reasonable.

(There isn't really any "standard" behavior for `--with-foo` options as far as I know, however.)

**Comment by zerothi** [comment]
No, ok, I agree there is no standard way. But... ;)

**Comment by stevengj** [comment]
In particular, the autoconf manual provides absolutely no guidance on what the meaning of the `--with-foo=bar` or `--enable-foo=bar` arguments should mean — it's completely up to the package, and in actual practice the usage varies widely.

**Comment by stevengj** [comment]
A PR for this would be welcome, though.

**Comment by stevengj** [comment]
`x = x"$LIBCTL_DIR"` tests that LIBCTL_DIR is an empty string, which is not what you want.  It should be sufficient to test `-r "$LIBCTL_DIR/share/libctl/base/ctl.scm"`

**Comment by zerothi** [comment]
True, copy-paste is a *****... Sorry.

Well I think the change is this small, I can make a pr if really needed, but it also seems a bit too excessive?

**Comment by stevengj** [comment]
A PR is the usual way to propose patches, big or small.

**Comment by bdice** [comment]
Ah! This also tripped me up when trying to build mpb for the first time just now. Thanks to @zerothi for filing an issue and making a PR.
