### ISSUE TITLE
Difficulties with mpb_data_analysis.py tutorial

### ISSUE THREAD

**Issue by JohnWeiner** [NanoComp/mpb#92]
This is a question about the dimensionality of the "converted" list of numpy arrays that appears in the code here:
```py
# Create an MPBData instance to transform the efields
md = mpb.MPBData(rectify=True, resolution=32, periods=3)
converted = []
for f in efields:
    # Get just the z component of the efields
    f = f[..., 0, 2]
    converted.append(md.convert(f))
print("converted shape =",np.shape(converted)) #I put this line in to get the shape the "converted" list.
for i, f in enumerate(converted):
    plt.subplot(331 + i)
    plt.contour(converted_eps.T, cmap='binary')
    plt.imshow(np.rot90(np.real(f).T), interpolation='spline36', cmap='RdBu', alpha=0.9)
    plt.axis('off')
fig=plt.gcf()
fig.dpi=400
plt.show()
```
The np.shape(converted) returns (8,96,83) meaning a list of 8 numpy arrays, 96x83 dimensionality.  I would have expected 96x96 (resolution of 32 * 3 periods).  The question is: Why is the column dimension on 83 instead of 96?  Does this have something to do with the conversion from skewed coordinates to rectangular coordinates?

**Comment by stevengj** [comment]
Yes.  Because the lattice isn't rectangular, the unit cell is a rhombus: in Cartesian coordinates (`rectify=True`), one unit cell is 96 pixels in one direction and 96 * √3/2 ≈ 83 pixels in the other direction.
