### ISSUE TITLE
super cell

### ISSUE THREAD

**Issue by Saranyanarayanan** [NanoComp/mpb#94]
Will it make the crystal finite if I define a super cell by increasing the size in geometry-lattice? or it just increases the size of the unit cell? While increasing the super cell dimension I could see that the bandstructure also changes. How do we incorporate the finiteness of the crystal in MPB?

**Comment by stevengj** [comment]
The boundary conditions in MPB are always periodic.  A supercell just increases the period, and is typically used for defect-mode calculations to compute "bound" modes that are exponentially localized (and hence are unaffected by the boundary conditions so long as they are sufficiently far away).

Whether you can calculate finite-crystal effects in MPB depends on what you want.  If you just want exponentially localized modes, a supercell is fine.  If you want to calculate scattering at an interface or radiation loss from a defect surrounded by a finite crystal, for example, then MPB is the wrong tool — you need something with absorbing boundaries (e.g. PML), like Meep.
