### ISSUE TITLE
On cygwin, configure MPB always got "Could not get required libctl liberay", how to fix it

### ISSUE THREAD

**Issue by genlintan** [NanoComp/mpb#97]
On my cygwin system, I have installed libctl library (/usr/local/share/libctl), I heve installed your meep-1.7
It is OK. But when I configure mpb (include 1.8, 1.7, 1.6, 1.5 version), always got error: couldn't find the required libctl library. I used : "git clone http://github.com/NanoComp/libctl.git", got success, but still got this error.  Configure partial result as follows:
checking for guile... yes
checking for guile-config... guile-config
checking if linking to guile works... yes
checking libguile.h usability... yes
checking libguile.h presence... yes
checking for libguile.h... yes
checking guile/gh.h usability... no
checking guile/gh.h presence... no
checking for guile/gh.h... no
checking for scm_make_smob_type... yes
checking for scm_array_get_handle... yes
checking for scm_is_array... yes
checking for SCM_SMOB_PREDICATE... yes
checking for SCM_SMOB_DATA... yes
checking for SCM_NEWSMOB... yes
checking how to activate readline in Guile... ice-9 readline
checking for libctl dir... /usr/local/share/libctl
checking for gen-ctl-io... gen-ctl-io
checking for ctl_get_vector3 in -lctl... no
configure: error: Couldn't find the required libctl library.

**Comment by stevengj** [comment]
Did you run `make install` for libctl?  Is there a `libctl` file in `/usr/local/lib`?

**Comment by genlintan** [comment]
On /usr/local/lib, there is libctl.
After I updated cygwin, maked again, this error didappeared.
Thank you very much

**Comment by mawc2019** [comment]
I am trapped in the same problem. After installing dependencies in **$HOME/install**, I configured MPB using
**./configure --prefix=$HOME/install --with-libctl=$HOME/install/share/libctl LDFLAGS="-L$HOME/install/lib" CPPFLAGS="-I$HOME/install/include"**
The same error was reported, i.e.,
**checking for ctl_get_vector3 in -lctl... no
configure: error: Couldn't find the required libctl library.**

I have already installed libctl-4.5.0 in **$HOME/install** with **make install**. The files are under **$HOME/install/share/libctl/base** and **$HOME/install/share/libctl/utils**.
