### ISSUE TITLE
Apparent Problem with the MPB Triangular-Lattice Tutorial

### ISSUE THREAD

**Issue by JohnWeiner** [NanoComp/mpb#99]
This issue appears also in NanoComp/meep.  Since it really has to do with MPB, I thought it might be more appropriate here.  
The mpb_tri_rods.py tutorial posits two basis vectors in reciprocal space (not real space). They are b1 = sqrt(3)/2 x + ½ y and b2 = sqrt(3)/2 x - ½ y. The x,y are cartesian basis vectors. One can specify the coordinates of the Γ,M,K,Γ points of the irreducible Brillouin zone using either the cartesian basis or the b1,b2 basis. Looking at the left inset of Fig. 10, Chapter 5 (p. 76) of Photonic Crystals...2nd ed., the coordinates of the three points of the Brillouin zone appear to be (in x,y basis):
Γ = 0,0
M = 0,1/2
K = 1/(2sqrt(3)), ½
In order to use the two basis vectors b1,b2 to express the Γ,M,K points, it is convenient to rotate them ccw by 120 deg. Then b2 is oriented along the +y axis. The two rotated b1,b2 basis vectors, expanded in the cartesian basis, are then:
b1 = -sqrt(3)/2 x + ½ y and b2= 0 x + 1 y.
Now the coefficients for the Γ, M, K points in the rotated (b1,b2) basis should be:
Γ = 0,0
M = 0,1/2
K = -⅓,+⅔
However, the tutorial specifies K = -⅓, +⅓ for the two coefficients, presumably in the (b1,b2) basis. It appears to me that a ⅓ coefficient for b2 will not give the correct y coordinate for K. The correct y value should be y = ½.
Any help with this issue would be greatly appreciated.

**Comment by JohnWeiner** [comment]
This issue has been resolved in the NanoComp/meep branch.

**Comment by stevengj** [comment]
For reference, some further explanation was added to the manual in 7d4b40a2b39a040516fb9f5e8951069b673f03eb along with this image:
![image](https://github.com/NanoComp/mpb/raw/7d4b40a2b39a040516fb9f5e8951069b673f03eb/doc/docs/images/tri-lattice.png)
